services:
  grist:
    image: gristlabs/grist
    restart: unless-stopped
    environment:
      - GRIST_IN_SERVICE=true
    ports:
      - '8484:8484'
    volumes:
      - 'grist:/persist'
volumes:
  grist:
